### ISSUE TITLE
Add checkerboard strategy

### ISSUE THREAD

**Issue by 4rm4** [traa-pixelcanvas/TraanvasBot#10]
`
class Checkerboard(Strategy):
    def __init__(self, bot, colors_ignored, colors_not_overwrite):
        self.bot = bot
        self.colors_ignored = colors_ignored
        self.colors_not_overwrite = colors_not_overwrite

    def apply(self):
        for y in xrange(self.bot.image.height):
            for x in xrange(self.bot.image.width):
                if (x + y) % 2 == 1:
                    continue;
                color = EnumColor.rgb(self.bot.image.pix[x,y], True)
                if self.bot.canvas.get_color(self.bot.start_x + x, self.bot.start_y + y) != color and not color in self.colors_ignored and self.bot.canvas.get_color(
                    self.bot.start_x + x,
                    self.bot.start_y + y) not in self.colors_not_overwrite:
                    self.bot.paint(self.bot.start_x + x, self.bot.start_y + y, color)
`

**Comment by aud-tree** [comment]
Doesn't `--draw_strategy qf` already do this?

**Comment by Mismatchia** [comment]
I thought so too, see the readme

**Comment by 4rm4** [comment]
QuickFill make small blocks of it, this one the entire line.

**Comment by 4rm4** [comment]
Closing the topic considering that QF is almost the same

**Comment by olegispe** [comment]
How would this work once the bot finishes, and needs to come back round.

**Comment by olegispe** [comment]
Would this only fill in a checkerboard, or would it continue round to completely finish it? Also for templates with even dimensions, this could look like a bunch of columns/rows rather than a checkerboard. Perhaps another way to do so, such as 

```python
def apply(self):
    for y in yrange:
        for x in self.xrange:
            if y % 2 == 0 and x % 2 == 1 or y % 2 == 1 and x % 2 == 0:
                color = EnumColor.rgb(self.bot.image.pix[x,y], True)
                old_color = self.bot.canvas.get_color(self.bot.start_x + x, self.bot.start_y + y)
                if old_color != color and not color in self.colors_ignored and \
                        old_color not in self.colors_not_overwrite and color.rgba[3] > 0:
                    self.bot.paint(self.bot.start_x + x, self.bot.start_y + y, color)
```

**Comment by aud-tree** [comment]
Even dimensions, sample 4x4 grid, each cell is the result of @4rm4's algo's paint condition `(x + y) % 2 == 0`:

| |0|1|2|3|
|-|-|-|-|-|
|0|T|F|T|F|
|1|F|T|F|T|
|2|T|F|T|F|
|3|F|T|F|T|

so I think you end up with a checkerboard either way. `(x + y) % 2 == 0` is a lot more succinct and understandable, I think.
