### ISSUE TITLE
Image quantization fails to replicate results of previous versions

### ISSUE THREAD

**Issue by Mismatchia** [traa-pixelcanvas/TraanvasBot#13]
Example: 
_Original image:_ 
![miko2](https://user-images.githubusercontent.com/49257776/55602469-58115380-57ad-11e9-8dc1-3a41f7919b48.png)
_Original quantization:_
![be41da83d6718e0f3580cabaf40af0bf](https://user-images.githubusercontent.com/49257776/55602482-6b242380-57ad-11e9-9958-b4a71f08a22a.png)
_Currently generated quantization:_
![be41da83d6718e0f3580cabaf40af0bf](https://user-images.githubusercontent.com/49257776/55602509-91e25a00-57ad-11e9-8b12-094163a0f055.png)

Probably has something to do with the color added by 4e7637b50d5714bae94d856fe994e8a34df3faa6

**Comment by aud-tree** [comment]
We were off by one with the colors. Fixed!
