### ISSUE TITLE
Feature request: Detect pixels updates as friendly or enemy

### ISSUE THREAD

**Issue by 4rm4** [traa-pixelcanvas/TraanvasBot#19]
Feature of identify the pixels updates as Enemy or Friendly and show the pixels painted by the user separated.

Exemple: 
`>> 01:55:31 ->Somebody updated -231,-2248 with green (FRIENDLY)`
`>> 01:55:31 ->Somebody updated -219,-2302 with red (ENEMY)`
`>> 01:55:31 ->You updated -238,-2328 with black`

**Comment by Mismatchia** [comment]
As of 9d6bd66afcac1d5b413478bf93bb5a549266ea3e, now shows [ALLY] and [ENEMY], but it can easily be changed to whatever other thing we prefer later :D
