### ISSUE TITLE
5xx page errors not caught

### ISSUE THREAD

**Issue by BrickGrass** [traa-pixelcanvas/TraanvasBot#33]
We have seen 4 instances of this bug, the site throws a 521 error using cloudflare, but the bot doesn't pre-empt this happening, so the error isn't caught, and the entire 521 page is passed through the code and printed in the terminal. Link to terminal print out below.

https://pastebin.com/JErtfPSJ

We also sometimes get 524 errors, 520 errors, and `requests.exceptions.ConnectionError`, all of which should be handled as part of this issue as well. Basically just handle any 5xx-class error that isn't already specifically handled.

Use a sane backoff algorithm to space out the retries so we don't spam the server when it's legitimately down.

**Comment by aud-tree** [comment]
It works!
