### ISSUE TITLE
Make bot output log file

### ISSUE THREAD

**Issue by Mismatchia** [traa-pixelcanvas/TraanvasBot#36]
Since changes to the UI in #29 will (hopefully temporarily) make scrolling through the history difficult, it would be good to have a log file output by the bot. Also it's just handy addition in general.

**Comment by olegispe** [comment]
Referencing commits 09f3732f215efb3181ff054cb513bac8003b8a96 and 3d1eae845f187d846846d970873ec514827d3e06 under branch [logging](https://github.com/traa-pixelcanvas/TraanvasBot/tree/logging) to this.

Request to merge?

**Comment by aud-tree** [comment]
Open a PR so I can briefly review it and then yeah

**Comment by olegispe** [comment]
Alright 👍

**Comment by olegispe** [comment]
All done. Free to close?

**Comment by aud-tree** [comment]
yep! go ahead and merge too.
