### ISSUE TITLE
Add vertical strategy

### ISSUE THREAD

**Issue by RussellJMeis** [traa-pixelcanvas/TraanvasBot#41]
It's actually simple. Just a matter of using linear and reversing the 

`        for y in self.yrange:
            for x in self.xrange:`

so it's 

`        for x in self.xrange:
            for y in self.yrange:`

**Comment by Mismatchia** [comment]
Implemented by 1e37593

**Comment by Bastique** [comment]
This was implimented wrong.   It should read: 
`for x in self.xrange: for y in self.yrange:`
But reads
`for x in self.yrange:
            for y in self.xrange:`

**Comment by Mismatchia** [comment]
Sorry! This was my fault for rushing things last night. It should be all fixed as of f1868a092b8cb9f308cbd698cabbb294e0a08c4b
