### ISSUE TITLE
ＭＡＸＩＭＵＭ　ＳＴＡＢＩＬＩＴＹ

### ISSUE THREAD

**Issue by aud-tree** [traa-pixelcanvas/TraanvasBot#49]
Implement a general error handling strategy that catches all known points of failure and either:

1. quits gracefully with a message if the error is fatal (e.g. can't load canvas or authenticate), or
2. retries every 5 seconds (bonus points for exponential backoff)

**Comment by olegispe** [comment]
I recommend reassigning [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook) to our own error handling function.

(This is safe, and the original function is available at [sys.__excepthook__](https://docs.python.org/3/library/sys.html#__sys.excepthook__).)

**Comment by aud-tree** [comment]
Hmm... the main issue I see with this is then `sys.excepthook` needs to know about the details of every possible error the bot can throw, and the recovery strategy is usually specific to where it occurs rather than the error type. For example, `requests.exceptions.ConnectionError` should retry during pixel placement, but not during chunk loading or auth. Worse, most of the crashes come from error responses after a network request, which don't involve an exception until we try to read the HTML body as JSON. In those cases, a JSON read error means very little, and we wouldn't have access to the response in the handler to figure out the correct action.

It's probably better to use inheritance, shared functions, decorators, or some other reusable method to handle errors in such a way that it's easy to specify which handler to use where.
