### ISSUE TITLE
Logging verbosity.

### ISSUE THREAD

**Issue by olegispe** [traa-pixelcanvas/TraanvasBot#56]
I feel as though verbosity would be useful, specifically to log upcoming features such as automatic time reduction, and also for in-waiting features such as retrying.

In `main.py` we could simply have 

```python
parser.add_argument('--verbose', required=False, default=False, dest='verbose')
```

and

```python
if args.verbose:
    logger.setLevel(logging.DEBUG)
else:
    logger.setLevel(logging.INFO)
```

We could then use `logger.info` for general logging, then `logger.debug` for when we want to test (as the name suggests.)

**Comment by Mismatchia** [comment]
We should also be using logging.ERROR I think. 
Also, error and debug messages should have their own formatting, such as something along the lines of `[ERROR]%(message)`, so that they're easily searchable in log files.

**Comment by olegispe** [comment]
Yeah, that would perfectly make sense 👍
