### ISSUE TITLE
Set i18n to unicode

### ISSUE THREAD

**Issue by Bastique** [traa-pixelcanvas/TraanvasBot#64]
Please add
`# -*- coding: utf-8 -*-`
to src/i18n.py
below 
`#!/usr/bin/env python`

This fixed a problem I had running the script on Windows after the French texts were added.

**Comment by Bastique** [comment]
This is the problem I fixed when I added it: 
![image](https://user-images.githubusercontent.com/32726771/56463247-44f1ac80-6385-11e9-8f54-7f9fbadf58ee.png)

**Comment by Mismatchia** [comment]
This is bad practice in Python 3, assuming we're dropping Python 2 support.

**Comment by aud-tree** [comment]
We have officially dropped Python 2 support, closing as wontfix
