### ISSUE TITLE
Bot sometimes gets caught painting the same pixel in a loop

### ISSUE THREAD

**Issue by Mismatchia** [traa-pixelcanvas/TraanvasBot#70]
Command used:
```sh
pipenv run python3 main.py -i .\img\giantFlag.png -f fingerprint -x 139735 -y -22357 -ds spiral -px 139835 -py -22178
```

Terminal output:
![2019-04-24_19-41-48](https://user-images.githubusercontent.com/49257776/56651822-0cc1d500-66c9-11e9-892c-c54cd5dd36bf.png)

The bot continues painting the same pixel until halted manually. It seems to have happened after a websocket disconnect, though I'm not sure if that's related. 

Restarting the bot seems to fix the issue.

**Comment by olegispe** [comment]
I would assume it's the websocket, seeing as the matrix is updated with your placement via the websocket, not via the strategy; I would guess the strategy doesn't think that it's done, so continues to keep trying?

**Comment by Mismatchia** [comment]
Seems you're right. I can't see any reason not to have the bot update the matrix itself when it receives a success response from the server. I think I'll add that.

This raises another question though: What caused the web socket connection to drop for so long? Did it stop trying to reconnect?

**Comment by Mismatchia** [comment]
Turns out the canvas update code is there, it's just indented too far -_-
https://github.com/traa-pixelcanvas/TraanvasBot/blob/44df62f475807ef0e98cf58ec08e585cc52927d3/src/bot.py#L86-L94

Who could be responsible for this?
![sublime_merge_2019-04-29_23-31-28](https://user-images.githubusercontent.com/49257776/56901282-fc4d9800-6ad6-11e9-9da9-4d3375a08ebd.png)
Ah c:

**Comment by Mismatchia** [comment]
68b1332 should resolve the issue with painting the same pixel infinitely when the websocket drops.
