### ISSUE TITLE
ANSI color codes are sent to log files

### ISSUE THREAD

**Issue by Mismatchia** [traa-pixelcanvas/TraanvasBot#74]
The ANSI color codes used to print colored text in the terminal are captured by the file logger, resulting in a jumbled mess when opened as plain text. 
EX:
![sublime_text_2019-04-25_14-23-04](https://user-images.githubusercontent.com/49257776/56710546-e0a86180-6765-11e9-9209-05ea5add2b17.png)

There do exist plugins for displaying these correctly, at least for Sublime Text, which looks like this:

![sublime_text_2019-04-25_14-26-46](https://user-images.githubusercontent.com/49257776/56710612-2e24ce80-6766-11e9-8a63-9c1e911fac8b.png)

Personally though, I think we should probably strip color codes before they're logged to a file, for simplicity reasons, such as being able to copy and paste logs in plain text.

**Comment by olegispe** [comment]
We could have a separate file handler strip colours before logging, or selectively log. I think making a separate handler makes more sense, but if it provides to be too difficult we don't have to.

We could just loop over the available colours and remove them from the strings, before logging.
