### ISSUE TITLE
KeyError: 'paint.waitsec'

### ISSUE THREAD

**Issue by 4n0nct** [traa-pixelcanvas/TraanvasBot#78]
Hello.
I can only only draw one pixel, it confirms it and then the script has this error:

`File "./main.py", line 142, in <module>`
`main()`
`File "./main.py", line 137, in main`
`run()`
`File "./main.py", line 126, in run`
`bot.run()`
`File "/home/x/TraanvasBot/src/bot.py", line 74, in run`
`self.strategy.apply()`
`File "/home/x/TraanvasBot/src/strategy.py", line 335, in apply`
`self.bot.paint(*self.scan_canvas())`
`File "/home/x/TraanvasBot/src/bot.py", line 96, in paint`
`return self.wait_time(response)`
`File "/home/x/TraanvasBot/src/bot.py", line 127, in wait_time`
`logger.debug(I18n.get('paint.waitsec')`
`File "/home/x/TraanvasBot/src/i18n.py", line 20, in get`
`return prefix + '[' + time.strftime("%H:%M:%S") + '] ' + I18n._all[I18n._locale][key] + suffix`
`KeyError: 'paint.waitsec'`

![2019-05-02_19-45](https://user-images.githubusercontent.com/50212348/57095359-f3490a80-6d12-11e9-98f6-c0708440a16a.png)

What could I edit to solve that ?
Thx by advance.

**Comment by olegispe** [comment]
This appears to be an issue with translations, please replace your `i18n.py` file in `src/` with the file of the same name in [i18n.zip](https://github.com/traa-pixelcanvas/TraanvasBot/files/3139304/i18n.zip). I'll create a fix for this so this doesn't happen again.

**Comment by 4n0nct** [comment]
Waow.
Thank you very much it works now.
(also, do you know how to make all these DEBUG:* disappear ?)

**Comment by olegispe** [comment]
Est-ce que tu utilises la version principale ou une autre version ? Vois si ta version est mise à jour en utilisant `git pull`, et si tu utilises la version `master`. 😃

**Comment by 4n0nct** [comment]
C'est bien à jour, mais ce n'est pas bien grave, c'était juste pour le confort. En tout cas merci beaucoup.
Veux-tu que je clos le fil ?

**Comment by olegispe** [comment]
Non, c'est bon, je vais le faire. Désolé de ne pouvoir résoudre ton autre problème.
